spring.application.name=financial-api

# MIGRATION
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/financial}
spring.datasource.username=${DB_USER_NAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT - expiration (ms) - refresh_expiration (ms)
jwt.secret=72f3f8fabf543f0659aa36e6f3c264cdbeed53b2bdec113ccddd77e2e3fc737e
jwt.expiration=3600000
jwt.refresh_expiration=86400000

# COOKIE
# Set to true in production (HTTPS only)
app.cookie.secure=false
# 7 days in seconds
app.cookie.access-token-max-age=604800
# 14 days in seconds
app.cookie.refresh-token-max-age=1209600
# Leave empty for current domain
app.cookie.domain=

# application-prod.properties
# app.cookie.secure=true
# app.cookie.access-token-max-age=604800
# app.cookie.refresh-token-max-age=1209600
# app.cookie.domain=.yourdomain.com