spring.application.name=${APP_NAME:financial-api}

# Migration
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=${FLYWAY_LOCATIONS:classpath:db/migration}

# Otp
otp.length=6

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/financial}
spring.datasource.username=${DB_USER_NAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}

app.mail.from=${MAIL_FROM:your_email@gmail.com}
app.mail.sender.name=${MAIL_SENDER_NAME:Pronity}


# JWT - expiration (1 hr - ms) - refresh_expiration ( 1day - ms) - reset_expiration ( 5 ms )
jwt.secret=${JWT_SECRET:72f3f8fabf543f0659aa36e6f3c264cdbeed53b2bdec113ccddd77e2e3fc737e}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refresh_expiration=${JWT_REFRESH_EXPIRATION:86400000}
jwt.reset_expiration=${JWT_RESET_EXPIRATION:300000}

# Cookie
# Set to true in production (HTTPS only)
app.cookie.secure=${COOKIE_SECURE:false}
# 15 minutes
app.cookie.access_token_max_age=${COOKIE_ACCESS_TOKEN_MAX_AGE:900}
# 7 days 
app.cookie.refresh_token_max_age=${COOKIE_REFRESH_TOKEN_MAX_AGE:604800}
# Leave empty for current domain
app.cookie.domain=${COOKIE_DOMAIN:}

# Server Configuration
server.port=8080

# OpenAPI Documentation (Spring Boot 3)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.financial.api.controller
springdoc.paths-to-match=/api/**

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:4200
cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
cors.allowed-headers=*
cors.exposed-headers=Authorization,Content-Disposition,X-Total-Count
cors.allow-credentials=true
cors.max-age=3600

# External Exchange Api
fastforex.api.key=${FASTFOREX_API_KEY:d17ee04710-37809ac763-t65r8d}

# Production (use application-prod.properties)
#cors.allowed-origins=https://app.yourcompany.com,https://admin.yourcompany.com


# Logging - Suppress Spring Security AuthenticationProvider warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG