spring.application.name=${APP_NAME:financial-api}

# MIGRATION
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=${FLYWAY_LOCATIONS:classpath:db/migration}

# DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/financial}
spring.datasource.username=${DB_USER_NAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT - expiration (ms) - refresh_expiration (ms)
jwt.secret=${JWT_SECRET:72f3f8fabf543f0659aa36e6f3c264cdbeed53b2bdec113ccddd77e2e3fc737e}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refresh_expiration=${JWT_REFRESH_EXPIRATION:86400000}

# COOKIE
# Set to true in production (HTTPS only)
app.cookie.secure=${COOKIE_SECURE:false}
# 15 minutes
app.cookie.access_token_max_age=${COOKIE_ACCESS_TOKEN_MAX_AGE:900}
# 7 days 
app.cookie.refresh_token_max_age=${COOKIE_REFRESH_TOKEN_MAX_AGE:604800}
# Leave empty for current domain
app.cookie.domain=${COOKIE_DOMAIN:}

# Server Configuration
server.port=8080

# OpenAPI Documentation (Spring Boot 3)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.financial.api.controller
springdoc.paths-to-match=/api/**

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:4200
cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
cors.allowed-headers=*
cors.exposed-headers=Authorization,Content-Disposition,X-Total-Count
cors.allow-credentials=true
cors.max-age=3600

# Production (use application-prod.properties)
#cors.allowed-origins=https://app.yourcompany.com,https://admin.yourcompany.com


# LOGGING - Suppress Spring Security AuthenticationProvider warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG